url: https://122e4e-bigemap.global.ssl.fastly.net
api: https://122e4e-bigemap.global.ssl.fastly.net/core
tileApi: https://api-maps-staging.tilestream.net
env: staging
source: docs
permalink: /:categories/:title/
baseurl: /bigemap.js
bigemapjs: v3.0.0
defaultid: 'bigemap.streets'
exclude: [dist]
future: true
