url: https://www.bigemap.com
api: https://www.bigemap.com/core
tileApi: https://api.bigemap.com
env: production
source: docs
permalink: /:categories/:title/
baseurl: /bigemap.js
bigemapjs: v3.1.1
defaultid: 'bigemap.streets'
exclude: [dist]
future: true
accessToken: pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejh2N21nMzAxMmQzMnA5emRyN2lucW0ifQ.jSE-g2vsn48Ry928pqylcg
